version: '3.7'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwordToUse123
    expose:
      - 3306
      - 33060
    volumes:
      - ./.configfile:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping' ]
      interval: 5s
      timeout: 5s
      retries: 10

  invenhelper:
    build: .
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/invenhelper?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=passwordToUse123
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy